# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mathieu\OneDrive\ModUpdater\ModUpdater v2\App.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Mathieu\\OneDrive\\ModUpdater\\ModUpdater v2\\../../Images/icône/MineCraft.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(:/trailer_thumbnail.png);\n"
"}\n"
"QPushButton {\n"
"    background-image: none;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QProgressBar {\n"
"    border-style: none;\n"
"    background-color: transparent;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"    background-color: #E4BB3F;\n"
"} ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.lblPfk = QtWidgets.QLabel(self.centralwidget)
        self.lblPfk.setGeometry(QtCore.QRect(200, 40, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPfk.setFont(font)
        self.lblPfk.setStyleSheet("background: rgba(255, 0, 0, 0);")
        self.lblPfk.setObjectName("lblPfk")
        self.rbtnAuto = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtnAuto.setGeometry(QtCore.QRect(260, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnAuto.setFont(font)
        self.rbtnAuto.setStyleSheet("background: rgba(255, 0, 0, 0);")
        self.rbtnAuto.setObjectName("rbtnAuto")
        self.rbtnOnce = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtnOnce.setGeometry(QtCore.QRect(260, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnOnce.setFont(font)
        self.rbtnOnce.setStyleSheet("background: rgba(255, 0, 0, 0);")
        self.rbtnOnce.setObjectName("rbtnOnce")
        self.rbtnRem = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtnRem.setGeometry(QtCore.QRect(260, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnRem.setFont(font)
        self.rbtnRem.setStyleSheet("background: rgba(255, 0, 0, 0);")
        self.rbtnRem.setObjectName("rbtnRem")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(20, 620, 75, 31))
        self.btnExit.setStyleSheet("")
        self.btnExit.setObjectName("btnExit")
        self.btnInstall = QtWidgets.QPushButton(self.centralwidget)
        self.btnInstall.setGeometry(QtCore.QRect(580, 620, 75, 31))
        self.btnInstall.setObjectName("btnInstall")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 520, 481, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lblPfk.raise_()
        self.rbtnOnce.raise_()
        self.rbtnRem.raise_()
        self.btnExit.raise_()
        self.btnInstall.raise_()
        self.rbtnAuto.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ModUpdater installer"))
        self.lblPfk.setText(_translate("MainWindow", "Pfk.ddns.net\'s Auto Mods Installer"))
        self.rbtnAuto.setText(_translate("MainWindow", "Auto Update Mods"))
        self.rbtnOnce.setText(_translate("MainWindow", "Update Mods Once"))
        self.rbtnRem.setText(_translate("MainWindow", "Uninstall Auto Updater"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.btnInstall.setText(_translate("MainWindow", "Install"))
import test1_rc
